use serde::{Deserialize, Serialize};

use crate::capability::Capability;

/// A discoverable identity card for an agent.
/// Built from `AgentConfig` at scheduler seed time; held by `ListAgentsTool`.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct AgentCard {
    pub id:          String,
    pub name:        String,
    pub description: String,
    pub skills:      Vec<String>,
}

impl From<&AgentConfig> for AgentCard {
    fn from(cfg: &AgentConfig) -> Self {
        Self {
            id:          cfg.id.clone(),
            name:        cfg.name.clone().unwrap_or_else(|| cfg.id.clone()),
            description: cfg.description.clone(),
            skills:      cfg.skills.clone(),
        }
    }
}

// deny_unknown_fields is intentionally omitted here to allow both [agent] and [[agents]]
// forms to coexist in the schema without serde rejecting the other key.
#[derive(Debug, Clone, Deserialize, Serialize)]
pub struct Config {
    pub agent: Option<AgentConfig>,
    #[serde(default)]
    pub agents: Vec<AgentConfig>,
    #[serde(default)]
    pub model: ModelConfig,
    #[serde(default)]
    pub tools: ToolsConfig,
    #[serde(default)]
    pub scheduler: SchedulerConfig,
    #[serde(default)]
    pub memory: MemoryConfig,
    /// Path for the flight log (JSONL). Defaults to "flight.jsonl" in the CWD.
    /// The --log-path CLI flag takes precedence over this field.
    pub log_path: Option<String>,
    /// Egress mediator configuration (p7.5+).
    #[serde(default)]
    pub egress: EgressConfig,
    /// Management HTTP API configuration (p7.7+).
    #[serde(default)]
    pub management: ManagementConfig,
    /// Credential broker configuration (cred.3+).
    #[serde(default)]
    pub credential_gateway: CredentialGatewayConfig,
    /// Config-declared sealed jobs (cap.2b). A `run_job(job_id)` call materializes a child
    /// with THIS declaration's fixed caps + rendered task template — never caller-chosen —
    /// so an injected, untrusted-data-reading agent can trigger predeclared work but cannot
    /// author privileged work. Empty by default (no jobs).
    #[serde(default)]
    pub jobs: Vec<Job>,
}

/// A config-declared sealed job (cap.2b). The trust root for a job-spawned child's
/// capabilities and task is THIS operator-authored declaration, not the (possibly injected)
/// agent that triggers it via `run_job`. `run_job` takes only a job id — no caps, no task
/// text, no free-form params — so there is no injection carrier: the caller cannot widen
/// caps (they come from `capabilities` here) nor redirect the work (the task comes from the
/// fixed `task` template, with only the server-stamped `{date}` substituted).
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct Job {
    /// Job id named by `run_job(job_id)` (e.g. "cos-inbox", "cos-curator").
    pub id: String,
    /// Per-child token ceiling.
    #[serde(default = "default_token_budget")]
    pub token_budget: u64,
    /// Per-child turn ceiling. Jobs do BOUNDED work (fetch mail, write a brief), unlike the
    /// always-on cron trigger, so this defaults generously rather than to the tiny agent
    /// default (`default_max_turns` = 20, which would trip `MaxTurnsReached` mid-pipeline —
    /// the cos-polish-adv-F5 class). `token_budget` remains the real spend bound.
    #[serde(default = "default_job_max_turns")]
    pub max_turns: u32,
    /// Fixed capability set attached to the spawned child. Config-trusted: the `run_job`
    /// path does NOT run the `capability_covered_by` parent-subset check (the caller need
    /// not — and for the de-privileged CoS trigger, must not — hold these).
    pub capabilities: Vec<Capability>,
    /// Fixed task template. The ONLY substitution is `{date}` (server-stamped at dispatch).
    /// No caller-supplied text ever reaches here — this is the injection firewall.
    pub task: String,
}

impl Job {
    /// Render the fixed task template with the server-stamped date. `{date}` is the only
    /// placeholder; `date` is generated by the scheduler (trusted), never caller-supplied.
    pub fn render(&self, date: &str) -> String {
        self.task.replace("{date}", date)
    }
}

/// Mutability class for a declared knowledge-base segment (p5.4+).
/// Re-exported from `memory::MutabilityClass` so config and runtime share one type.
pub use crate::memory::MutabilityClass as SegmentClass;

/// A single operator-seeded entry written to a segment at startup (p5.9/F-14).
///
/// Used to populate `canon` trust anchors that agents cannot write themselves.
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct SeedEntry {
    pub key: String,
    pub value: String,
}

/// A declared knowledge-base segment (p5.4+).
///
/// ```toml
/// [[memory.segments]]
/// name  = "project:notes"    # namespace agents reference in kb_put/kb_get
/// class = "log"              # "canon" | "log" | "scratch"
/// seed  = [                  # p5.9: operator-seeded entries (e.g. canon anchors)
///   { key = "guidelines", value = "Cite evidence." },
/// ]
/// ```
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct SegmentConfig {
    pub name: String,
    pub class: SegmentClass,
    /// Operator-seeded entries written to the segment at startup (F-14). The
    /// operator write bypasses agent-facing canon protection by design.
    #[serde(default)]
    pub seed: Vec<SeedEntry>,
}

/// Configuration for the durable key/value memory store (p5.1+).
///
/// ```toml
/// [memory]
/// store_path             = "memory.redb"   # relative to CWD or absolute
/// enabled                = true
/// max_entries_per_segment = 500            # p5.6: evict oldest beyond this
/// max_entry_age_days      = 90             # p5.6: evict entries older than N days
/// distill_on_complete     = false          # p5.6: summarise short-term → Tier 3
///
/// [[memory.segments]]          # p5.4: declare shared KB segments
/// name  = "project:notes"
/// class = "log"
/// ```
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct MemoryConfig {
    /// Path to the redb database file.
    /// Relative paths are resolved relative to the CWD at startup.
    /// Absolute paths are used as-is.
    /// Container/production deployments should set an absolute path on a persistent
    /// mount, e.g. `store_path = "/run/memory/memory.redb"` (p5.3.5 detachable volume).
    #[serde(default = "default_memory_store_path")]
    pub store_path: String,
    /// Set to false to disable the memory store entirely.
    /// When false, `kv_get` and `kv_set` tools are not registered.
    #[serde(default = "default_memory_enabled")]
    pub enabled: bool,
    /// Declared shared KB segments (p5.4+). Each entry fixes the segment's
    /// mutability class in the store at startup.
    #[serde(default)]
    pub segments: Vec<SegmentConfig>,
    /// Per-segment capacity limit (p5.6). Oldest entries are evicted first once the
    /// count exceeds this value. `None` (the default) means no capacity-based eviction.
    #[serde(default)]
    pub max_entries_per_segment: Option<usize>,
    /// Per-segment age limit in days (p5.6). Entries older than this are evicted.
    /// `None` (the default) means no age-based eviction.
    #[serde(default)]
    pub max_entry_age_days: Option<u64>,
    /// When true, each completed agent's short-term memory buffer is distilled into
    /// a single Tier-3 inference summary at the end of the run (p5.6).
    /// Default false — existing demos unchanged.
    #[serde(default)]
    pub distill_on_complete: bool,
}

fn default_memory_store_path() -> String {
    "memory.redb".to_string()
}

fn default_memory_enabled() -> bool {
    true
}

impl Default for MemoryConfig {
    fn default() -> Self {
        Self {
            store_path:               default_memory_store_path(),
            enabled:                  default_memory_enabled(),
            segments:                 Vec::new(),
            max_entries_per_segment:  None,
            max_entry_age_days:       None,
            distill_on_complete:      false,
        }
    }
}

/// Configuration for the egress mediator and tamper-evident audit log (p7.5+).
///
/// ```toml
/// [egress]
/// evidence_path = "evidence.jsonl"   # default
/// key_path      = "egress-key.pkcs8" # default; created on first run
/// proxy_addr    = "127.0.0.1:8765"   # optional: bind HTTP stub (p7.5b readiness)
/// ```
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct EgressConfig {
    /// Path to the tamper-evident action receipt log.
    #[serde(default = "default_evidence_path")]
    pub evidence_path: String,
    /// Path to the Ed25519 private key (PKCS8 DER). Created automatically on first run.
    #[serde(default = "default_egress_key_path")]
    pub key_path: String,
    /// If set, bind an HTTP stub server on this address (always returns 501).
    /// Fail-closed: agentd exits non-zero if bind fails.
    #[serde(default)]
    pub proxy_addr: Option<String>,
}

fn default_evidence_path() -> String {
    "evidence.jsonl".to_string()
}
fn default_egress_key_path() -> String {
    "egress-key.pkcs8".to_string()
}

impl Default for EgressConfig {
    fn default() -> Self {
        Self {
            evidence_path: default_evidence_path(),
            key_path:      default_egress_key_path(),
            proxy_addr:    None,
        }
    }
}

/// Management HTTP API configuration (p7.7+).
///
/// Exposes scheduler state as JSON + SSE so agentctl can run on the Mac/Linux
/// host without FUSE access. Off by default; enable via `[management] enabled = true`.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ManagementConfig {
    /// Enable the management API. Defaults to false.
    #[serde(default)]
    pub enabled: bool,
    /// TCP port to bind (loopback only). Defaults to 7999.
    #[serde(default = "default_management_port")]
    pub port: u16,
    /// Bind address. Must resolve to loopback unless `allow_non_loopback` is set;
    /// agentd refuses to start otherwise.
    #[serde(default = "default_management_bind_addr")]
    pub bind_addr: String,
    /// Explicit deployment opt-in to bind a non-loopback address (e.g. `0.0.0.0`
    /// so a container's `-p` mapping can reach it from the host). The management
    /// API is unauthenticated; setting this exposes spawn/inject/approve/deny to
    /// every peer that can reach the bound address. Defaults to false.
    #[serde(default)]
    pub allow_non_loopback: bool,
}

fn default_management_port() -> u16 {
    7999
}
fn default_management_bind_addr() -> String {
    "127.0.0.1".to_string()
}

impl Default for ManagementConfig {
    fn default() -> Self {
        Self {
            enabled:            false,
            port:               default_management_port(),
            bind_addr:          default_management_bind_addr(),
            allow_non_loopback: false,
        }
    }
}

impl ManagementConfig {
    /// Apply environment variable overrides. Called after TOML config is parsed.
    /// `AGENTD_MANAGEMENT_ENABLED=true` enables the management API without editing TOML.
    /// `AGENTD_MANAGEMENT_PORT=<n>` overrides the port.
    pub fn apply_env_overrides(&mut self) {
        if std::env::var("AGENTD_MANAGEMENT_ENABLED").as_deref() == Ok("true") {
            self.enabled = true;
        }
        if let Ok(port_str) = std::env::var("AGENTD_MANAGEMENT_PORT") {
            if let Ok(p) = port_str.parse::<u16>() {
                self.port = p;
            }
        }
    }
}

/// Authentication style for a credential provider adapter (cred.3+).
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "kebab-case")]
pub enum AuthStyle {
    /// RFC 6750 Bearer token: `Authorization: Bearer <token>`
    OauthBearer,
    /// API key in a named request header.
    ApiKeyHeader,
    /// API key as a URL query parameter.
    ApiKeyQuery,
}

/// TOML configuration for one credential provider adapter (cred.3+).
///
/// ```toml
/// [credential_gateway.providers.google]
/// auth_style    = "oauth-bearer"
/// upstream_base = "https://www.googleapis.com"
/// token_path    = "/run/secrets/google.json"
/// state_path    = "/data/state/oauth/google.json"
///
/// [credential_gateway.providers.brave-search]
/// auth_style    = "api-key-header"
/// upstream_base = "https://api.search.brave.com"
/// header_name   = "X-Subscription-Token"
/// secret_key    = "BRAVE_SEARCH_API_KEY"
/// ```
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct ProviderConfig {
    pub auth_style:    AuthStyle,
    pub upstream_base: String,
    /// Named header for `api-key-header` style (also scrubbed from caller requests).
    #[serde(default)]
    pub header_name:   Option<String>,
    /// Optional prefix prepended as `"{prefix} {credential}"` for `api-key-header`
    /// style. Required for APIs that expect `Authorization: Bearer <token>` instead
    /// of a raw token value. Must not contain `\r` or `\n` (validated at startup).
    #[serde(default)]
    pub header_value_prefix: Option<String>,
    /// Env var that holds the API key for `api-key-header` / `api-key-query` styles.
    #[serde(default)]
    pub secret_key:    Option<String>,
    /// Path to the JSON secrets file (OAuth flows); e.g. `/run/secrets/google.json`.
    #[serde(default)]
    pub token_path:    Option<String>,
    /// Path for writing runtime token state (OAuth access + refresh rotation).
    #[serde(default)]
    pub state_path:    Option<String>,
    /// Per-agent per-provider request-count cap enforced at the broker layer.
    /// `None` (default) = unlimited. `0` = block all requests to this provider.
    #[serde(default)]
    pub max_requests_per_agent: Option<u64>,
    /// Allowlist of query-parameter names forwarded to the upstream API.
    /// Default (empty) = no params forwarded (preserves D3 injection prevention).
    /// Only the listed param names are passed; all others are silently dropped.
    #[serde(default)]
    pub passthrough_query_params: Vec<String>,
}

/// Configuration for the in-process credential broker (cred.3+).
///
/// ```toml
/// [credential_gateway]
/// enabled = true
///
/// [credential_gateway.providers.google]
/// auth_style    = "oauth-bearer"
/// upstream_base = "https://www.googleapis.com"
/// token_path    = "/run/secrets/google.json"
/// state_path    = "/data/state/oauth/google.json"
/// ```
#[derive(Debug, Clone, Serialize, Deserialize, Default)]
pub struct CredentialGatewayConfig {
    /// Enable the credential broker. Defaults to false (off by default, opt-in).
    #[serde(default)]
    pub enabled: bool,
    /// Provider adapters keyed by provider name (lowercase, kebab-case).
    #[serde(default)]
    pub providers: std::collections::HashMap<String, ProviderConfig>,
    /// Path for the per-agent request-cap persistence database (`caps.redb`).
    /// Defaults to `None` = in-memory only (resets on agentd restart).
    /// Set by `main.rs` to `<memory_store_dir>/caps.redb` when the credential
    /// gateway is enabled, so caps survive restarts without operator config.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub caps_db_path: Option<String>,
}

impl Config {
    /// Returns AgentConfigs from either the `[agent]` or `[[agents]]` TOML form.
    /// Errors if both are set (ambiguous), or neither is set unless
    /// `[scheduler] allow_empty_agents = true` (in which case returns an empty
    /// Vec). Duplicate agent ids are NOT checked here — the scheduler rejects
    /// them at registration/spawn time (`scheduler.rs`, "already in use").
    pub fn agent_configs(&self) -> anyhow::Result<Vec<AgentConfig>> {
        match (&self.agent, self.agents.is_empty()) {
            (Some(_), false) => anyhow::bail!(
                "cannot set both [agent] and [[agents]] in the same config; use one form"
            ),
            (None, true) if self.scheduler.allow_empty_agents => Ok(vec![]),
            (None, true) => anyhow::bail!(
                "no agents configured; set [agent] for a single agent or [[agents]] for multiple \
                 (or set [scheduler] allow_empty_agents = true to start with zero agents)"
            ),
            (Some(a), true) => Ok(vec![a.clone()]),
            (None, false) => Ok(self.agents.clone()),
        }
    }
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct SchedulerConfig {
    /// Global token ceiling across all agents. 0 = unlimited.
    ///
    /// When `budget_reset_interval` > 0 this is a *per-window* ceiling, not a
    /// lifetime one: spend since the current window's start is compared against
    /// it, and the window rolls over every `budget_reset_interval` seconds. When
    /// the interval is 0 (default) this is a lifetime ceiling — which, on a 24/7
    /// agent, permanently denies once exhausted (audit86-P0-2). See ux.8′.
    #[serde(default)]
    pub global_token_budget: u64,
    /// Rolling budget-window length in seconds. 0 = no reset (lifetime ceiling,
    /// the legacy behavior). Set to 86400 for a daily window on an always-on
    /// deployment so the budget rebases instead of self-bricking (audit86-P0-2 /
    /// D2). Applies to both the global ceiling and per-agent `token_budget`.
    #[serde(default)]
    pub budget_reset_interval: u64,
    /// Maximum number of in-flight inference calls at once. 0 = unlimited.
    #[serde(default)]
    pub max_concurrent_inferences: usize,
    /// Maximum spawn nesting depth. 0 = spawning disabled. Default 4.
    #[serde(default = "default_max_spawn_depth")]
    pub max_spawn_depth: u32,
    /// Checkpoint the full scheduler state every N completed turns (after tool results).
    /// 0 = SIGTERM/SIGINT only. Default 1 (every turn).
    #[serde(default = "default_checkpoint_interval_turns")]
    pub checkpoint_interval_turns: u32,
    /// When `true`, `Config::agent_configs()` accepts a config with neither `[agent]`
    /// nor `[[agents]]` set, returning an empty agent list instead of erroring.
    /// Opt-in only — used by cockpit mode to cold-start `agentd` with no agents so
    /// the management API and FUSE surface come up for an operator to spawn into.
    #[serde(default)]
    pub allow_empty_agents: bool,
}

fn default_max_spawn_depth() -> u32 {
    4
}

fn default_checkpoint_interval_turns() -> u32 {
    1
}

impl Default for SchedulerConfig {
    fn default() -> Self {
        Self {
            global_token_budget:       0,
            budget_reset_interval:     0,
            max_concurrent_inferences: 0,
            max_spawn_depth:           default_max_spawn_depth(),
            checkpoint_interval_turns: default_checkpoint_interval_turns(),
            allow_empty_agents:        false,
        }
    }
}

/// Input to the `spawn_agent` tool — describes the child agent to create.
/// Capabilities and max_turns inherit from parent when absent.
#[derive(Debug, Clone, serde::Deserialize)]
pub struct SpawnConfig {
    /// If absent, auto-generated as `"{parent_id}-child-{seq}"`.
    pub child_id: Option<String>,
    /// The child's initial task (first user message).
    pub task: String,
    /// Scheduling priority. Default 0.
    #[serde(default)]
    pub priority: u32,
    /// Per-agent token ceiling. Inherits parent's remaining budget if absent.
    pub token_budget: Option<u64>,
    /// Capabilities requested for the child (cap.2 spawn attenuation).
    /// `None` — the field is absent OR explicitly `null` (serde treats them identically) —
    /// = inherit the parent's full set (backward compat). Note: `null` never *exceeds* the
    /// parent, it just declines to attenuate, same as omitting the field.
    /// `Some(set)` = the child's requested set, validated ⊆ parent at spawn time
    /// (`capability_covered_by`); any cap outside the parent rejects the whole spawn.
    /// `Some([])` = no capability-GATED tools. Capability-free convenience tools
    /// (`send_message`, `request_approval`, `list_agents`, memory tools) whose
    /// `required_capability_for` is `None` are still visible — see `filtered_specs`.
    /// This bounds an *honest* orchestrator / accidental over-grant — it is a
    /// least-privilege FLOOR, not injection defense (the orchestrator chooses these and
    /// is itself downstream of untrusted data).
    #[serde(default)]
    pub capabilities: Option<Vec<Capability>>,
}

/// The action an agent is requesting approval for. Passed by the agent as the
/// input to the `request_approval` tool; stored in `ParkedApproval` until resolved.
///
/// `kind` and `risk` are free-form strings in v1 (the harness defines taxonomy).
/// `linked` is intentionally absent — cross-action coordination is harness territory.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct PendingActionRequest {
    /// Short noun phrase: the action type, e.g. "write_file", "send_email".
    pub kind:       String,
    /// Operator-visible severity: "low" | "medium" | "high" (free-form in v1).
    pub risk:       String,
    /// One-sentence human summary of what the agent intends to do.
    pub summary:    String,
    /// Full argument set the agent will pass to the underlying tool once approved.
    /// The operator may override these via the `edits` field on Approve.
    pub args:       serde_json::Value,
    /// Optional snapshot of state before the action (diff context for the operator).
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub prev_state: Option<serde_json::Value>,
    /// Optional snapshot of state after the action would complete.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub new_state:  Option<serde_json::Value>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct AgentConfig {
    pub id: String,
    #[serde(default)]
    pub task: String,
    #[serde(default = "default_max_turns")]
    pub max_turns: u32,
    #[serde(default = "default_token_budget")]
    pub token_budget: u64,
    /// Scheduling priority. Higher value runs before lower. Default 0 (equal priority).
    #[serde(default)]
    pub priority: u32,
    /// Tool capabilities granted to this agent.
    /// `None` (field absent) = unrestricted access to all registered tools.
    /// `Some([])` = deny all tool use.
    /// `Some([...])` = allow only the listed capabilities.
    #[serde(default)]
    pub capabilities: Option<Vec<Capability>>,
    /// Display name for this agent. Defaults to `id` if absent.
    #[serde(default)]
    pub name: Option<String>,
    /// Human-readable description of this agent's purpose.
    #[serde(default)]
    pub description: String,
    /// Free-form skill tags this agent advertises.
    #[serde(default)]
    pub skills: Vec<String>,
    /// Execution tier. Default: native (in-process). Set to "universal" to run as
    /// an external child process. Requires `command` to be set.
    #[serde(default)]
    pub tier: AgentTier,
    /// Executable path for universal-tier agents. Ignored for native-tier agents.
    #[serde(default)]
    pub command: Option<String>,
    /// Additional arguments passed to the command. Static only (no template substitution).
    #[serde(default)]
    pub args: Vec<String>,
    /// Isolation mode for universal-tier agents. "none" (default) or "gvisor".
    /// Requires `runsc` on PATH when set to "gvisor".
    #[serde(default)]
    pub isolation: IsolationMode,
    /// Maximum wall-clock seconds before the universal agent is killed. 0 = no limit.
    #[serde(default)]
    pub max_wall_seconds: u64,
}

pub fn default_max_turns() -> u32 {
    20
}

/// Default turn ceiling for a sealed [[jobs]] child (cap.2b). Generous because a job runs a
/// bounded pipeline (OAuth + fetch ~20 messages + KB writes, or read + assemble + publish) that
/// needs far more than the 20-turn agent default; `token_budget` is the real spend bound.
pub fn default_job_max_turns() -> u32 {
    1000
}

pub fn default_token_budget() -> u64 {
    100_000
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct ModelConfig {
    #[serde(default = "default_provider")]
    pub provider: String,
    #[serde(default = "default_model")]
    pub model: String,
    #[serde(default = "default_max_tokens")]
    pub max_tokens: u32,
    /// When true, use SSE streaming and print text chunks progressively to stdout.
    /// Applies to all agents in this config file. Default: true.
    #[serde(default = "default_streaming")]
    pub streaming: bool,
}

fn default_streaming() -> bool {
    true
}

fn default_provider() -> String {
    "anthropic".to_string()
}

fn default_model() -> String {
    "claude-sonnet-4-6".to_string()
}

fn default_max_tokens() -> u32 {
    4096
}

impl Default for ModelConfig {
    fn default() -> Self {
        Self {
            provider: default_provider(),
            model: default_model(),
            max_tokens: default_max_tokens(),
            streaming: true,
        }
    }
}

#[derive(Debug, Clone, Serialize, Deserialize, Default)]
#[serde(deny_unknown_fields)]
pub struct ToolsConfig {
    #[serde(default)]
    pub native: Vec<String>,
    #[serde(default)]
    pub mcp_servers: Vec<McpServerConfig>,
    /// When `true`, startup fails if any MCP server omits the `capabilities` field.
    /// Ensures all servers are sandboxed; defaults to `false` for backward compat.
    #[serde(default)]
    pub mcp_require_capabilities: bool,
}

/// Execution tier for an agent.
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Default)]
#[serde(rename_all = "lowercase")]
pub enum AgentTier {
    /// In-process Rust agent (default). Uses the full inference loop.
    #[default]
    Native,
    /// External process wrapped in optional gVisor isolation (p7.6).
    /// Requires `command`, routes LLM traffic through the egress proxy.
    Universal,
}

/// Isolation mode for an MCP server subprocess or a universal-tier agent.
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Default)]
#[serde(rename_all = "lowercase")]
pub enum IsolationMode {
    /// Default: Landlock + seccomp + Linux namespaces applied via pre_exec.
    #[default]
    None,
    /// Stronger isolation: wrap the server command with `runsc do` (gVisor).
    /// Requires `runsc` on PATH; fails fast at startup if not found.
    /// Landlock/seccomp/namespaces are NOT applied (gVisor's Sentry handles isolation).
    Gvisor,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct McpServerConfig {
    pub name: String,
    /// Subprocess command for stdio transport. Required when `url` is absent.
    /// Must be empty when `url` is set (the two are mutually exclusive).
    #[serde(default)]
    pub command: String,
    #[serde(default)]
    pub args: Vec<String>,
    /// HTTP endpoint for Streamable HTTP transport (MCP spec 2025-03-26).
    /// When set, the server is contacted over HTTP/SSE instead of spawning a subprocess.
    /// Must start with `https://`. Mutually exclusive with `command`.
    #[serde(default)]
    pub url: Option<String>,
    /// Maps HTTP header names to environment variable names whose values are the header values.
    /// Example: `{ Authorization = "LINEAR_MCP_TOKEN" }` reads `$LINEAR_MCP_TOKEN` at startup
    /// and sends it as the `Authorization` header on every request.
    /// The env var value (e.g. `"Bearer sk-lin-..."`) is the full header value, sent as-is.
    /// Note: OAuth-based servers require a future `auth_provider` field; only static tokens here.
    #[serde(default)]
    pub headers_env: std::collections::HashMap<String, String>,
    /// Capability-based sandbox rules applied to this MCP server subprocess (stdio only).
    /// `None` (field absent) = no sandbox — server runs unrestricted.
    /// `Some([])` = deny-all spawn + network isolation; no filesystem grants.
    /// `Some([...])` = exact capability set converted to Landlock + seccomp + namespace rules.
    /// Ignored for HTTP servers (externally isolated).
    #[serde(default)]
    pub capabilities: Option<Vec<Capability>>,
    /// Stronger isolation mode for stdio servers. `"none"` (default): pre_exec sandbox.
    /// `"gvisor"`: wrap command with `runsc do`; requires `runsc` on PATH.
    /// Ignored for HTTP servers.
    #[serde(default)]
    pub isolation: IsolationMode,
    /// Extra environment variables to pass to this MCP server subprocess (stdio only).
    /// Applied on top of the standard allowlist (PATH, HOME, USER, LANG, LC_ALL, TMPDIR).
    /// The parent process's full environment, including secrets, is NOT inherited.
    /// Ignored for HTTP servers (use `headers_env` for HTTP auth headers).
    #[serde(default)]
    pub env: std::collections::HashMap<String, String>,
    /// Names of environment variables from the parent process to forward to this MCP server.
    /// Use this for API keys the subprocess needs (e.g. `BRAVE_SEARCH_API_KEY`).
    /// Each name is looked up in the parent env at startup; missing vars are silently skipped.
    /// Ignored for HTTP servers (use `headers_env` instead).
    #[serde(default)]
    pub passenv: Vec<String>,
    /// Allow `http://` (plaintext) URLs for this HTTP MCP server.
    /// Only set this for Docker-internal peer services where TLS is not needed
    /// because traffic stays within the container network. Never use for
    /// external URLs — tokens would be sent in clear text.
    /// A startup warning is emitted when this flag is set.
    #[serde(default)]
    pub allow_insecure_local: bool,
    /// When true, tools advertised by this MCP server silently shadow any
    /// already-registered native tool with the same name. Use to let a remote
    /// semantic KB (`kb_put`/`kb_get`/`kb_search`) transparently replace the
    /// built-in Layer-1 BM25 tools. Operators must opt in explicitly; default
    /// false means accidental name collisions produce a hard error.
    #[serde(default)]
    pub tool_override: bool,
}

impl McpServerConfig {
    /// Returns true if this server uses HTTP transport.
    pub fn is_http(&self) -> bool {
        self.url.is_some()
    }

    /// Validate transport config: exactly one of url/command must be set; url must be https.
    pub fn validate(&self) -> anyhow::Result<()> {
        match (&self.url, self.command.is_empty()) {
            (Some(_), false) => anyhow::bail!(
                "MCP server '{}': cannot set both 'url' and 'command' — \
                 use 'url' for HTTP transport or 'command' for stdio transport",
                self.name
            ),
            (None, true) => anyhow::bail!(
                "MCP server '{}': transport is 'stdio' but no command is set — \
                 add command = \"/path/to/server\" for stdio or url = \"https://...\" for HTTP",
                self.name
            ),
            (Some(url), true) => {
                if url.starts_with("http://") {
                    if !self.allow_insecure_local {
                        anyhow::bail!(
                            "MCP server '{}': url must start with 'https://' (got {:?}) — \
                             plaintext HTTP is not allowed (tokens would be sent in clear text). \
                             For Docker-internal peer services set allow_insecure_local = true.",
                            self.name, url
                        );
                    }
                    // Reject credentials embedded in http:// URLs too — same invariant applies.
                    let after_scheme = url.strip_prefix("http://").unwrap_or(url);
                    let slash = after_scheme.find('/').unwrap_or(after_scheme.len());
                    if after_scheme[..slash].contains('@') {
                        anyhow::bail!(
                            "MCP server '{}': embedding credentials in the URL is not allowed — \
                             use 'headers_env' to inject auth headers from environment variables",
                            self.name
                        );
                    }
                    // allow_insecure_local=true: permitted but warn at startup.
                    tracing::warn!(
                        server = %self.name,
                        url = url.as_str(),
                        "allow_insecure_local=true: connecting to HTTP MCP server over plaintext — \
                         only safe for Docker-internal peer services"
                    );
                    return Ok(());
                }
                if !url.starts_with("https://") {
                    anyhow::bail!(
                        "MCP server '{}': url must start with 'https://' (got {:?}) — \
                         plaintext HTTP is not allowed (tokens would be sent in clear text)",
                        self.name, url
                    );
                }
                // Reject credentials embedded in the URL (e.g. https://user:token@host/mcp)
                // which would persist secrets to disk, violating the secrets-from-env invariant.
                // Use headers_env to inject auth headers from environment variables instead.
                let after_scheme = &url["https://".len()..];
                let slash = after_scheme.find('/').unwrap_or(after_scheme.len());
                if after_scheme[..slash].contains('@') {
                    anyhow::bail!(
                        "MCP server '{}': embedding credentials in the URL is not allowed — \
                         use 'headers_env' to inject auth headers from environment variables",
                        self.name
                    );
                }
                Ok(())
            }
            (None, false) => Ok(()), // stdio, command present
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn management_config_default_denies_non_loopback() {
        let cfg = ManagementConfig::default();
        assert_eq!(cfg.bind_addr, "127.0.0.1");
        assert!(!cfg.allow_non_loopback);
    }

    #[test]
    fn management_config_parses_allow_non_loopback_opt_in() {
        let raw = r#"
enabled = true
bind_addr = "0.0.0.0"
allow_non_loopback = true
"#;
        let cfg: ManagementConfig = toml::from_str(raw).unwrap();
        assert_eq!(cfg.bind_addr, "0.0.0.0");
        assert!(cfg.allow_non_loopback);
    }

    #[test]
    fn management_config_omitted_allow_non_loopback_defaults_false() {
        // Distinct from `management_config_default_denies_non_loopback` (which
        // tests `ManagementConfig::default()` directly): this exercises the
        // `#[serde(default)]` attribute through a real `toml::from_str` parse,
        // the actual code path a deployment's TOML file goes through.
        let raw = r#"
enabled = true
"#;
        let cfg: ManagementConfig = toml::from_str(raw).unwrap();
        assert!(!cfg.allow_non_loopback);
    }

    #[test]
    fn full_config_round_trips() {
        let raw = r#"
[agent]
id = "scout"
task = "list the project dir and summarize Cargo.toml"
max_turns = 10
token_budget = 50000

[model]
provider = "anthropic"
model = "claude-sonnet-4-6"
max_tokens = 2048

[tools]
native = ["read_file", "list_dir"]
"#;
        let cfg: Config = toml::from_str(raw).unwrap();
        assert_eq!(cfg.agent.as_ref().unwrap().id, "scout");
        assert_eq!(cfg.agent.as_ref().unwrap().max_turns, 10);
        assert_eq!(cfg.agent.as_ref().unwrap().token_budget, 50_000);
        assert_eq!(cfg.model.provider, "anthropic");
        assert_eq!(cfg.model.model, "claude-sonnet-4-6");
        assert_eq!(cfg.model.max_tokens, 2048);
        assert_eq!(cfg.tools.native, vec!["read_file", "list_dir"]);
    }

    // F-14/F-15: the shipped multi-agent memory demo MUST parse and be runnable.
    // It is the smoke test for the whole memory subsystem; CI runs `cargo test`,
    // so this guards against a non-parsing demo shipping again.
    #[test]
    fn shipped_demo_agents_toml_parses_and_is_runnable() {
        let raw = include_str!("../agents.toml");
        let cfg: Config = toml::from_str(raw)
            .expect("shipped agents.toml must parse (F-14: e.g. unknown `seed` field)");

        // F-15: the writer needs spawn_agent registered, not just the Spawn cap.
        assert!(
            cfg.tools.native.iter().any(|t| t == "spawn_agent"),
            "demo grants Spawn but must also list spawn_agent in [tools].native (F-15)"
        );

        // F-14: the canon segment must carry its operator seed.
        let canon = cfg
            .memory
            .segments
            .iter()
            .find(|s| matches!(s.class, SegmentClass::Canon))
            .expect("demo must declare a canon segment");
        assert!(
            !canon.seed.is_empty(),
            "canon trust-anchor segment must be operator-seeded (F-14)"
        );

        // The writer agent must hold Spawn so the spawn flow actually runs.
        let writer = cfg
            .agents
            .iter()
            .find(|a| a.id == "writer")
            .expect("demo must define the writer agent");
        assert!(writer.capabilities.is_some(), "writer must declare capabilities");
    }

    #[test]
    fn model_defaults_apply_when_section_absent() {
        let raw = r#"
[agent]
id = "minimal"
"#;
        let cfg: Config = toml::from_str(raw).unwrap();
        assert_eq!(cfg.model.provider, "anthropic");
        assert_eq!(cfg.model.model, "claude-sonnet-4-6");
        assert_eq!(cfg.model.max_tokens, 4096);
        assert_eq!(cfg.agent.as_ref().unwrap().max_turns, 20);
        assert_eq!(cfg.agent.as_ref().unwrap().token_budget, 100_000);
    }

    #[test]
    fn missing_agent_id_is_error() {
        let raw = r#"
[agent]
task = "no id here"
"#;
        let result: Result<Config, _> = toml::from_str(raw);
        assert!(result.is_err(), "expected Err when agent.id is missing");
    }

    #[test]
    fn agent_config_rejects_unknown_fields() {
        // deny_unknown_fields still applies on AgentConfig itself
        let raw = r#"
[agent]
id = "scout"
unknown_field = "bad"
"#;
        let result: Result<Config, _> = toml::from_str(raw);
        assert!(result.is_err(), "expected Err for unknown field in [agent]");
    }

    #[test]
    fn top_level_unknown_field_is_now_allowed() {
        // Config no longer has deny_unknown_fields — extra top-level keys are silently ignored
        let raw = r#"
[agent]
id = "scout"

[typo_section]
foo = "bar"
"#;
        let result: Result<Config, _> = toml::from_str(raw);
        assert!(result.is_ok(), "unknown top-level section should be ignored now");
    }

    #[test]
    fn agent_configs_single_agent_form() {
        let raw = r#"
[agent]
id = "solo"
task = "do something"
"#;
        let cfg: Config = toml::from_str(raw).unwrap();
        let cfgs = cfg.agent_configs().unwrap();
        assert_eq!(cfgs.len(), 1);
        assert_eq!(cfgs[0].id, "solo");
    }

    #[test]
    fn agent_configs_multi_agent_form() {
        let raw = r#"
[[agents]]
id = "alpha"
task = "task a"

[[agents]]
id = "beta"
task = "task b"
"#;
        let cfg: Config = toml::from_str(raw).unwrap();
        let cfgs = cfg.agent_configs().unwrap();
        assert_eq!(cfgs.len(), 2);
        assert_eq!(cfgs[0].id, "alpha");
        assert_eq!(cfgs[1].id, "beta");
    }

    #[test]
    fn agent_configs_both_set_is_error() {
        let raw = r#"
[agent]
id = "solo"
task = "task"

[[agents]]
id = "alpha"
task = "task a"
"#;
        let cfg: Config = toml::from_str(raw).unwrap();
        let result = cfg.agent_configs();
        assert!(result.is_err(), "expected Err when both [agent] and [[agents]] are set");
        assert!(result.unwrap_err().to_string().contains("cannot set both"));
    }

    #[test]
    fn agent_configs_neither_set_is_error() {
        let raw = r#"
[model]
model = "claude-sonnet-4-6"
"#;
        let cfg: Config = toml::from_str(raw).unwrap();
        let result = cfg.agent_configs();
        assert!(result.is_err(), "expected Err when neither [agent] nor [[agents]] is set");
        assert!(result.unwrap_err().to_string().contains("no agents configured"));
    }

    #[test]
    fn agent_configs_allows_empty_when_opted_in() {
        let raw = r#"
[scheduler]
allow_empty_agents = true
"#;
        let cfg: Config = toml::from_str(raw).unwrap();
        let cfgs = cfg.agent_configs().unwrap();
        assert!(cfgs.is_empty(), "expected an empty agent list, not an error");
    }

    #[test]
    fn agent_configs_still_rejects_empty_by_default() {
        let raw = r#"
[scheduler]
allow_empty_agents = false
"#;
        let cfg: Config = toml::from_str(raw).unwrap();
        let result = cfg.agent_configs();
        assert!(
            result.is_err(),
            "allow_empty_agents = false must still reject a zero-agent config"
        );
        assert!(result.unwrap_err().to_string().contains("no agents configured"));
    }

    // /review (ux.9, testing specialist): the (Some(_), false) match arm is matched
    // before the (None, true) allow_empty_agents arm, so ambiguous configs are
    // rejected regardless of the flag — but that safety was only implicit in arm
    // ordering, unasserted by any test. Guards against a future refactor (e.g. into
    // if/else) silently inverting the precedence.
    #[test]
    fn agent_configs_both_set_is_error_even_with_allow_empty_agents() {
        let raw = r#"
[scheduler]
allow_empty_agents = true

[agent]
id = "solo"
task = "task"

[[agents]]
id = "alpha"
task = "task a"
"#;
        let cfg: Config = toml::from_str(raw).unwrap();
        let result = cfg.agent_configs();
        assert!(
            result.is_err(),
            "allow_empty_agents=true must not bypass the both-set ambiguity check"
        );
        assert!(result.unwrap_err().to_string().contains("cannot set both"));
    }

    // /review (ux.9, testing specialist): docker/cockpit.toml is now what the
    // Docker image's default CMD boots — a silent future schema drift (renamed
    // field, a deny_unknown_fields added elsewhere) would break the new zero-arg
    // default with nothing in CI to catch it before a manual `docker run`.
    // Mirrors shipped_demo_agents_toml_parses_and_is_runnable's F-14/F-15 guard.
    #[test]
    fn shipped_cockpit_toml_parses_and_boots_empty() {
        let raw = include_str!("../../docker/cockpit.toml");
        let cfg: Config = toml::from_str(raw).expect("shipped docker/cockpit.toml must parse");
        assert!(
            cfg.scheduler.allow_empty_agents,
            "cockpit.toml must opt into allow_empty_agents (it ships zero [[agents]])"
        );
        assert!(
            cfg.management.enabled,
            "cockpit.toml must enable the management API (the HTTP-fallback readiness path depends on it)"
        );
        let cfgs = cfg.agent_configs().expect("cockpit.toml must produce a valid (empty) agent list");
        assert!(cfgs.is_empty(), "cockpit.toml must boot with zero agents by design");
    }

    #[test]
    fn scheduler_config_explicit_values_parse() {
        let raw = r#"
[agent]
id = "a"

[scheduler]
global_token_budget = 1000
max_concurrent_inferences = 4
"#;
        let cfg: Config = toml::from_str(raw).unwrap();
        assert_eq!(cfg.scheduler.global_token_budget, 1000);
        assert_eq!(cfg.scheduler.max_concurrent_inferences, 4);
    }

    #[test]
    fn scheduler_config_defaults_to_unlimited() {
        let raw = r#"
[agent]
id = "a"
"#;
        let cfg: Config = toml::from_str(raw).unwrap();
        assert_eq!(cfg.scheduler.global_token_budget, 0, "0 means unlimited");
        assert_eq!(cfg.scheduler.max_concurrent_inferences, 0, "0 means unlimited");
        assert_eq!(cfg.scheduler.max_spawn_depth, 4, "default spawn depth must be 4");
    }

    #[test]
    fn scheduler_config_max_spawn_depth_explicit() {
        let raw = r#"
[agent]
id = "a"

[scheduler]
max_spawn_depth = 2
"#;
        let cfg: Config = toml::from_str(raw).unwrap();
        assert_eq!(cfg.scheduler.max_spawn_depth, 2);
    }

    #[test]
    fn scheduler_config_default_impl_has_spawn_depth_4() {
        // SchedulerConfig::default() must return max_spawn_depth=4 so that
        // Rust-constructed configs (as used in tests) are not silently broken.
        let sc = SchedulerConfig::default();
        assert_eq!(sc.max_spawn_depth, 4);
    }

    #[test]
    fn spawn_config_deserializes_task_only() {
        let raw = r#"{"task": "do the thing"}"#;
        let sc: SpawnConfig = serde_json::from_str(raw).unwrap();
        assert_eq!(sc.task, "do the thing");
        assert!(sc.child_id.is_none());
        assert_eq!(sc.priority, 0);
        assert!(sc.token_budget.is_none());
    }

    #[test]
    fn spawn_config_deserializes_all_fields() {
        let raw = r#"{"task":"sub","child_id":"my-child","priority":5,"token_budget":50000}"#;
        let sc: SpawnConfig = serde_json::from_str(raw).unwrap();
        assert_eq!(sc.task, "sub");
        assert_eq!(sc.child_id.as_deref(), Some("my-child"));
        assert_eq!(sc.priority, 5);
        assert_eq!(sc.token_budget, Some(50_000));
    }

    #[test]
    fn spawn_config_missing_task_is_error() {
        let raw = r#"{"child_id": "orphan"}"#;
        let result: Result<SpawnConfig, _> = serde_json::from_str(raw);
        assert!(result.is_err(), "SpawnConfig requires `task`");
    }

    #[test]
    fn agent_priority_parses_from_toml() {
        let raw = r#"
[[agents]]
id = "high"
task = "task"
priority = 10

[[agents]]
id = "low"
task = "task"
"#;
        let cfg: Config = toml::from_str(raw).unwrap();
        let cfgs = cfg.agent_configs().unwrap();
        assert_eq!(cfgs[0].priority, 10);
        assert_eq!(cfgs[1].priority, 0, "absent priority defaults to 0");
    }

    #[test]
    fn capabilities_absent_defaults_to_none() {
        let raw = r#"
[agent]
id = "a"
task = "task"
"#;
        let cfg: Config = toml::from_str(raw).unwrap();
        let cfgs = cfg.agent_configs().unwrap();
        assert!(cfgs[0].capabilities.is_none(), "absent capabilities = unrestricted");
    }

    #[test]
    fn capabilities_empty_array_is_deny_all() {
        let raw = r#"
[agent]
id = "a"
task = "task"
capabilities = []
"#;
        let cfg: Config = toml::from_str(raw).unwrap();
        let cfgs = cfg.agent_configs().unwrap();
        assert_eq!(cfgs[0].capabilities, Some(vec![]));
    }

    #[test]
    fn capabilities_fs_read_round_trip() {
        let raw = r#"
[agent]
id = "a"
task = "task"
capabilities = [{ FsRead = { prefix = "/workspace" } }]
"#;
        let cfg: Config = toml::from_str(raw).unwrap();
        let cfgs = cfg.agent_configs().unwrap();
        assert_eq!(
            cfgs[0].capabilities,
            Some(vec![Capability::FsRead {
                prefix: "/workspace".to_string()
            }])
        );
    }

    #[test]
    fn capabilities_multiple_variants_round_trip() {
        let raw = r#"
[agent]
id = "a"
task = "task"
capabilities = [
  { FsRead = { prefix = "/workspace" } },
  { FsWrite = { prefix = "/tmp" } },
  { Mcp = { server = "echo", tools = ["echo_text"] } },
]
"#;
        let cfg: Config = toml::from_str(raw).unwrap();
        let cfgs = cfg.agent_configs().unwrap();
        let caps = cfgs[0].capabilities.as_ref().unwrap();
        assert_eq!(caps.len(), 3);
        assert_eq!(caps[0], Capability::FsRead { prefix: "/workspace".to_string() });
        assert_eq!(caps[1], Capability::FsWrite { prefix: "/tmp".to_string() });
        assert_eq!(
            caps[2],
            Capability::Mcp {
                server: "echo".to_string(),
                tools: vec!["echo_text".to_string()]
            }
        );
    }

    // ── p3.3: McpServerConfig capability field tests ─────────────────────────

    #[test]
    fn mcp_server_capabilities_absent_defaults_to_none() {
        let raw = r#"
[agent]
id = "a"
task = "t"

[[tools.mcp_servers]]
name = "echo"
command = "/usr/bin/echo"
"#;
        let cfg: Config = toml::from_str(raw).unwrap();
        assert_eq!(cfg.tools.mcp_servers.len(), 1);
        assert!(cfg.tools.mcp_servers[0].capabilities.is_none(),
            "absent capabilities field should default to None");
    }

    #[test]
    fn mcp_server_capabilities_empty_array_is_deny_all() {
        let raw = r#"
[agent]
id = "a"
task = "t"

[[tools.mcp_servers]]
name = "echo"
command = "/usr/bin/echo"
capabilities = []
"#;
        let cfg: Config = toml::from_str(raw).unwrap();
        assert_eq!(cfg.tools.mcp_servers[0].capabilities, Some(vec![]));
    }

    #[test]
    fn mcp_server_capabilities_with_fs_rules() {
        let raw = r#"
[agent]
id = "a"
task = "t"

[[tools.mcp_servers]]
name = "echo"
command = "/usr/bin/echo"
capabilities = [
  { FsRead = { prefix = "/workspace" } },
  { FsWrite = { prefix = "/tmp" } },
]
"#;
        let cfg: Config = toml::from_str(raw).unwrap();
        let caps = cfg.tools.mcp_servers[0].capabilities.as_ref().unwrap();
        assert_eq!(caps.len(), 2);
        assert_eq!(caps[0], Capability::FsRead { prefix: "/workspace".into() });
        assert_eq!(caps[1], Capability::FsWrite { prefix: "/tmp".into() });
    }

    // ── p4.2: IsolationMode + isolation field tests ──────────────────────────

    #[test]
    fn mcp_server_isolation_defaults_to_none() {
        let raw = r#"
[agent]
id = "a"
task = "t"

[[tools.mcp_servers]]
name = "echo"
command = "/usr/bin/echo"
"#;
        let cfg: Config = toml::from_str(raw).unwrap();
        assert_eq!(cfg.tools.mcp_servers[0].isolation, IsolationMode::None);
    }

    #[test]
    fn mcp_server_isolation_gvisor_parses() {
        let raw = r#"
[agent]
id = "a"
task = "t"

[[tools.mcp_servers]]
name = "secure"
command = "/usr/bin/python3"
isolation = "gvisor"
"#;
        let cfg: Config = toml::from_str(raw).unwrap();
        assert_eq!(cfg.tools.mcp_servers[0].isolation, IsolationMode::Gvisor);
    }

    #[test]
    fn mcp_server_isolation_unknown_value_is_error() {
        let raw = r#"
[agent]
id = "a"
task = "t"

[[tools.mcp_servers]]
name = "echo"
command = "/usr/bin/echo"
isolation = "firecracker"
"#;
        let result: Result<Config, _> = toml::from_str(raw);
        assert!(result.is_err(), "unknown isolation value should fail to parse");
    }

    // ── p4.1: mcp_require_capabilities tests ─────────────────────────────────

    #[test]
    fn mcp_require_capabilities_defaults_to_false() {
        let raw = r#"
[agent]
id = "a"
task = "t"
"#;
        let cfg: Config = toml::from_str(raw).unwrap();
        assert!(!cfg.tools.mcp_require_capabilities,
            "mcp_require_capabilities must default to false");
    }

    #[test]
    fn mcp_require_capabilities_true_parses() {
        let raw = r#"
[agent]
id = "a"
task = "t"

[tools]
mcp_require_capabilities = true
"#;
        let cfg: Config = toml::from_str(raw).unwrap();
        assert!(cfg.tools.mcp_require_capabilities);
    }

    // ── p4.5: log_path config field tests ────────────────────────────────────

    #[test]
    fn log_path_absent_defaults_to_none() {
        let raw = r#"
[agent]
id = "a"
task = "t"
"#;
        let cfg: Config = toml::from_str(raw).unwrap();
        assert!(cfg.log_path.is_none(), "absent log_path must default to None");
    }

    #[test]
    fn log_path_parses_when_set() {
        let raw = r#"
log_path = "/var/log/agentd/flight.jsonl"

[agent]
id = "a"
task = "t"
"#;
        let cfg: Config = toml::from_str(raw).unwrap();
        assert_eq!(cfg.log_path.as_deref(), Some("/var/log/agentd/flight.jsonl"));
    }

    // ── p7.1: HTTP MCP server config tests ────────────────────────────────────

    #[test]
    fn http_server_config_round_trips() {
        let raw = r#"
[agent]
id = "a"
task = "t"

[[tools.mcp_servers]]
name = "linear"
url = "https://mcp.linear.app/mcp"
headers_env = { Authorization = "LINEAR_MCP_TOKEN" }
"#;
        let cfg: Config = toml::from_str(raw).unwrap();
        let srv = &cfg.tools.mcp_servers[0];
        assert_eq!(srv.name, "linear");
        assert_eq!(srv.url.as_deref(), Some("https://mcp.linear.app/mcp"));
        assert_eq!(srv.headers_env.get("Authorization").map(|s| s.as_str()), Some("LINEAR_MCP_TOKEN"));
        assert!(srv.command.is_empty(), "command defaults to empty for HTTP server");
    }

    #[test]
    fn http_server_validate_ok() {
        let raw = r#"
[agent]
id = "a"
task = "t"

[[tools.mcp_servers]]
name = "linear"
url = "https://mcp.linear.app/mcp"
"#;
        let cfg: Config = toml::from_str(raw).unwrap();
        assert!(cfg.tools.mcp_servers[0].validate().is_ok());
    }

    #[test]
    fn http_server_validate_rejects_http_url() {
        let raw = r#"
[agent]
id = "a"
task = "t"

[[tools.mcp_servers]]
name = "bad"
url = "http://insecure.example.com/mcp"
"#;
        let cfg: Config = toml::from_str(raw).unwrap();
        let err = cfg.tools.mcp_servers[0].validate().unwrap_err();
        assert!(err.to_string().contains("https://"), "got: {err}");
    }

    #[test]
    fn both_url_and_command_is_validation_error() {
        let raw = r#"
[agent]
id = "a"
task = "t"

[[tools.mcp_servers]]
name = "bad"
url = "https://example.com/mcp"
command = "/usr/bin/server"
"#;
        let cfg: Config = toml::from_str(raw).unwrap();
        let err = cfg.tools.mcp_servers[0].validate().unwrap_err();
        assert!(err.to_string().contains("both"), "got: {err}");
    }

    #[test]
    fn stdio_server_validate_rejects_missing_command() {
        let raw = r#"
[agent]
id = "a"
task = "t"

[[tools.mcp_servers]]
name = "files"
"#;
        let cfg: Config = toml::from_str(raw).unwrap();
        let err = cfg.tools.mcp_servers[0].validate().unwrap_err();
        assert!(err.to_string().contains("no command"), "got: {err}");
    }

    #[test]
    fn is_http_returns_true_for_url_server() {
        let raw = r#"
[agent]
id = "a"
task = "t"

[[tools.mcp_servers]]
name = "linear"
url = "https://mcp.linear.app/mcp"
"#;
        let cfg: Config = toml::from_str(raw).unwrap();
        assert!(cfg.tools.mcp_servers[0].is_http());
    }

    #[test]
    fn is_http_returns_false_for_stdio_server() {
        let raw = r#"
[agent]
id = "a"
task = "t"

[[tools.mcp_servers]]
name = "echo"
command = "/usr/bin/echo"
"#;
        let cfg: Config = toml::from_str(raw).unwrap();
        assert!(!cfg.tools.mcp_servers[0].is_http());
    }

    #[test]
    fn headers_env_defaults_to_empty() {
        let raw = r#"
[agent]
id = "a"
task = "t"

[[tools.mcp_servers]]
name = "echo"
command = "/usr/bin/echo"
"#;
        let cfg: Config = toml::from_str(raw).unwrap();
        assert!(cfg.tools.mcp_servers[0].headers_env.is_empty());
    }

    #[test]
    fn http_server_validate_rejects_url_with_embedded_credentials() {
        let raw = r#"
[agent]
id = "a"
task = "t"

[[tools.mcp_servers]]
name = "bad"
url = "https://user:secret@mcp.example.com/mcp"
"#;
        let cfg: Config = toml::from_str(raw).unwrap();
        let err = cfg.tools.mcp_servers[0].validate().unwrap_err();
        assert!(err.to_string().contains("headers_env"), "got: {err}");
    }

    #[test]
    fn http_server_validate_rejects_non_https_scheme() {
        let raw = r#"
[agent]
id = "a"
task = "t"

[[tools.mcp_servers]]
name = "bad"
url = "ftp://example.com/mcp"
"#;
        let cfg: Config = toml::from_str(raw).unwrap();
        let err = cfg.tools.mcp_servers[0].validate().unwrap_err();
        assert!(err.to_string().contains("https://"), "got: {err}");
    }

    // ── p4.7: McpServerConfig.env field tests ────────────────────────────────

    #[test]
    fn mcp_server_env_field_parses() {
        let raw = r#"
[agent]
id = "a"
task = "t"

[[tools.mcp_servers]]
name = "echo"
command = "/usr/bin/echo"

[tools.mcp_servers.env]
MY_KEY = "my_value"
OTHER = "42"
"#;
        let cfg: Config = toml::from_str(raw).unwrap();
        let env = &cfg.tools.mcp_servers[0].env;
        assert_eq!(env.get("MY_KEY").map(|s| s.as_str()), Some("my_value"));
        assert_eq!(env.get("OTHER").map(|s| s.as_str()), Some("42"));
    }

    #[test]
    fn mcp_server_env_defaults_to_empty() {
        let raw = r#"
[agent]
id = "a"
task = "t"

[[tools.mcp_servers]]
name = "echo"
command = "/usr/bin/echo"
"#;
        let cfg: Config = toml::from_str(raw).unwrap();
        assert!(cfg.tools.mcp_servers[0].env.is_empty(),
            "absent env field must default to empty map");
    }

    // ── p5.1: MemoryConfig tests ──────────────────────────────────────────────

    #[test]
    fn memory_config_defaults_when_section_absent() {
        let raw = r#"
[agent]
id = "a"
task = "t"
"#;
        let cfg: Config = toml::from_str(raw).unwrap();
        assert_eq!(cfg.memory.store_path, "memory.redb");
        assert!(cfg.memory.enabled);
    }

    #[test]
    fn memory_config_explicit_values_parse() {
        let raw = r#"
[agent]
id = "a"
task = "t"

[memory]
store_path = "/var/lib/agentd/mem.redb"
enabled = false
"#;
        let cfg: Config = toml::from_str(raw).unwrap();
        assert_eq!(cfg.memory.store_path, "/var/lib/agentd/mem.redb");
        assert!(!cfg.memory.enabled);
    }

    // ── p5.6: eviction config tests ──────────────────────────────────────────

    #[test]
    fn memory_config_eviction_fields_default_to_none_and_false() {
        let raw = r#"
[agent]
id = "a"
task = "t"
"#;
        let cfg: Config = toml::from_str(raw).unwrap();
        assert!(cfg.memory.max_entries_per_segment.is_none(), "max_entries_per_segment defaults None");
        assert!(cfg.memory.max_entry_age_days.is_none(), "max_entry_age_days defaults None");
        assert!(!cfg.memory.distill_on_complete, "distill_on_complete defaults false");
    }

    #[test]
    fn memory_config_eviction_fields_parse() {
        let raw = r#"
[agent]
id = "a"
task = "t"

[memory]
max_entries_per_segment = 500
max_entry_age_days = 90
distill_on_complete = true
"#;
        let cfg: Config = toml::from_str(raw).unwrap();
        assert_eq!(cfg.memory.max_entries_per_segment, Some(500));
        assert_eq!(cfg.memory.max_entry_age_days, Some(90));
        assert!(cfg.memory.distill_on_complete);
    }

    #[test]
    fn capabilities_kb_write_round_trip() {
        let raw = r#"
[agent]
id = "a"
task = "t"
capabilities = [{ KbWrite = { segment = "agent:scratch" } }]
"#;
        let cfg: Config = toml::from_str(raw).unwrap();
        let caps = cfg.agent_configs().unwrap();
        assert_eq!(
            caps[0].capabilities,
            Some(vec![Capability::KbWrite { segment: "agent:scratch".to_string() }])
        );
    }

    #[test]
    fn capabilities_kb_read_round_trip() {
        let raw = r#"
[agent]
id = "a"
task = "t"
capabilities = [{ KbRead = { segment = "agent:scratch" } }]
"#;
        let cfg: Config = toml::from_str(raw).unwrap();
        let caps = cfg.agent_configs().unwrap();
        assert_eq!(
            caps[0].capabilities,
            Some(vec![Capability::KbRead { segment: "agent:scratch".to_string() }])
        );
    }

    // ── p5.4: SegmentConfig / SegmentClass tests ──────────────────────────────

    #[test]
    fn segment_config_log_class_parses() {
        let raw = r#"
[agent]
id = "a"
task = "t"

[[memory.segments]]
name = "kb:events"
class = "log"
"#;
        let cfg: Config = toml::from_str(raw).unwrap();
        assert_eq!(cfg.memory.segments.len(), 1);
        assert_eq!(cfg.memory.segments[0].name, "kb:events");
        assert!(matches!(cfg.memory.segments[0].class, crate::config::SegmentClass::Log));
    }

    #[test]
    fn segment_config_canon_class_parses() {
        let raw = r#"
[agent]
id = "a"
task = "t"

[[memory.segments]]
name = "kb:docs"
class = "canon"
"#;
        let cfg: Config = toml::from_str(raw).unwrap();
        assert!(matches!(cfg.memory.segments[0].class, crate::config::SegmentClass::Canon));
    }

    #[test]
    fn segment_config_scratch_class_parses() {
        let raw = r#"
[agent]
id = "a"
task = "t"

[[memory.segments]]
name = "kb:scratch"
class = "scratch"
"#;
        let cfg: Config = toml::from_str(raw).unwrap();
        assert!(matches!(cfg.memory.segments[0].class, crate::config::SegmentClass::Scratch));
    }

    #[test]
    fn segment_config_multiple_segments_parse() {
        let raw = r#"
[agent]
id = "a"
task = "t"

[[memory.segments]]
name = "kb:log"
class = "log"

[[memory.segments]]
name = "kb:canon"
class = "canon"

[[memory.segments]]
name = "kb:notes"
class = "scratch"
"#;
        let cfg: Config = toml::from_str(raw).unwrap();
        assert_eq!(cfg.memory.segments.len(), 3);
        assert_eq!(cfg.memory.segments[0].name, "kb:log");
        assert_eq!(cfg.memory.segments[1].name, "kb:canon");
        assert_eq!(cfg.memory.segments[2].name, "kb:notes");
    }

    #[test]
    fn segment_config_invalid_class_is_error() {
        let raw = r#"
[agent]
id = "a"
task = "t"

[[memory.segments]]
name = "kb:bad"
class = "invalid"
"#;
        let result: Result<Config, _> = toml::from_str(raw);
        assert!(result.is_err(), "unknown segment class must fail to parse");
    }

    #[test]
    fn memory_config_defaults_have_empty_segments() {
        let raw = r#"
[agent]
id = "a"
task = "t"
"#;
        let cfg: Config = toml::from_str(raw).unwrap();
        assert!(cfg.memory.segments.is_empty(), "default segments must be empty");
    }

    // ── p1.6: AgentCard tests ─────────────────────────────────────────────────

    #[test]
    fn agent_card_name_defaults_to_id() {
        let cfg = AgentConfig {
            id:              "scout".to_string(),
            task:            String::new(),
            max_turns:       20,
            token_budget:    100_000,
            priority:        0,
            capabilities:    None,
            name:            None,
            description:     String::new(),
            skills:          vec![],
            tier:            AgentTier::Native,
            command:         None,
            args:            vec![],
            isolation:       IsolationMode::None,
            max_wall_seconds: 0,
        };
        let card = AgentCard::from(&cfg);
        assert_eq!(card.id, "scout");
        assert_eq!(card.name, "scout", "name should default to id when absent");
        assert_eq!(card.description, "");
        assert!(card.skills.is_empty());
    }

    #[test]
    fn agent_card_explicit_name_and_skills() {
        let cfg = AgentConfig {
            id:              "reader".to_string(),
            task:            String::new(),
            max_turns:       20,
            token_budget:    100_000,
            priority:        0,
            capabilities:    None,
            name:            Some("File Reader".to_string()),
            description:     "Reads files".to_string(),
            skills:          vec!["read".to_string(), "summarize".to_string()],
            tier:            AgentTier::Native,
            command:         None,
            args:            vec![],
            isolation:       IsolationMode::None,
            max_wall_seconds: 0,
        };
        let card = AgentCard::from(&cfg);
        assert_eq!(card.name, "File Reader");
        assert_eq!(card.description, "Reads files");
        assert_eq!(card.skills, vec!["read", "summarize"]);
    }

    #[test]
    fn agent_config_name_description_skills_parse_from_toml() {
        let raw = r#"
[agent]
id = "assistant"
name = "My Assistant"
description = "A helpful assistant"
skills = ["research", "write"]
"#;
        let cfg: Config = toml::from_str(raw).unwrap();
        let ac = cfg.agent.unwrap();
        assert_eq!(ac.name.as_deref(), Some("My Assistant"));
        assert_eq!(ac.description, "A helpful assistant");
        assert_eq!(ac.skills, vec!["research", "write"]);
    }

    // ── h8.1: allow_insecure_local + tool_override tests ─────────────────────

    #[test]
    fn http_server_allow_insecure_local_ok() {
        // T8: http:// URL accepted when allow_insecure_local = true.
        let raw = r#"
[agent]
id = "a"
task = "t"

[[tools.mcp_servers]]
name = "semantic-kb"
url = "http://semantic-kb-mcp:8020"
allow_insecure_local = true
"#;
        let cfg: Config = toml::from_str(raw).unwrap();
        let srv = &cfg.tools.mcp_servers[0];
        assert!(srv.allow_insecure_local, "flag should round-trip");
        assert!(srv.validate().is_ok(), "http:// with allow_insecure_local must not error");
    }

    #[test]
    fn http_server_insecure_local_rejected_without_flag() {
        // T9: http:// URL rejected by default (allow_insecure_local = false).
        let raw = r#"
[agent]
id = "a"
task = "t"

[[tools.mcp_servers]]
name = "semantic-kb"
url = "http://semantic-kb-mcp:8020"
"#;
        let cfg: Config = toml::from_str(raw).unwrap();
        let err = cfg.tools.mcp_servers[0].validate().unwrap_err();
        assert!(
            err.to_string().contains("allow_insecure_local"),
            "error must mention allow_insecure_local, got: {err}"
        );
    }

    #[test]
    fn tool_override_field_defaults_false() {
        // T11: tool_override defaults to false (accidental shadowing is an error).
        let raw = r#"
[agent]
id = "a"
task = "t"

[[tools.mcp_servers]]
name = "semantic-kb"
url = "https://example.com/mcp"
"#;
        let cfg: Config = toml::from_str(raw).unwrap();
        assert!(!cfg.tools.mcp_servers[0].tool_override, "must default to false");
    }

    #[test]
    fn tool_override_field_parses_true() {
        // T10 (config side): tool_override = true round-trips correctly.
        let raw = r#"
[agent]
id = "a"
task = "t"

[[tools.mcp_servers]]
name = "semantic-kb"
url = "http://semantic-kb-mcp:8020"
allow_insecure_local = true
tool_override = true
"#;
        let cfg: Config = toml::from_str(raw).unwrap();
        assert!(cfg.tools.mcp_servers[0].tool_override, "flag should round-trip");
    }

    #[test]
    fn http_insecure_local_rejects_embedded_credentials() {
        // T11-creds: allow_insecure_local=true must still reject credentials embedded in the URL —
        // violates the secrets-from-env constitutional invariant.
        let raw = r#"
[agent]
id = "a"
task = "t"

[[tools.mcp_servers]]
name = "semantic-kb"
url = "http://user:secretpassword@qdrant:6333"
allow_insecure_local = true
"#;
        let cfg: Config = toml::from_str(raw).unwrap();
        let err = cfg.tools.mcp_servers[0].validate().unwrap_err();
        assert!(
            err.to_string().contains("embedding credentials"),
            "expected embedded-credentials error, got: {err}"
        );
    }

    // -----------------------------------------------------------------------
    // cos.agents.toml correctness guards
    // These tests parse the real CoS config files and assert prompt hygiene
    // invariants that are easy to regress without a compile-time check.
    // -----------------------------------------------------------------------

    /// Every shipped copy of the CoS prompts. The dev config is what Docker boots
    /// (`Dockerfile`), the overlay is what QEMU boots (`agentd.config=/etc/agentd/...`), and
    /// the templates are what `agentctl spawn` instantiates. A prompt-hygiene invariant that
    /// only holds in one of them is a deployment that silently runs the old behaviour —
    /// brief.1 shipped exactly that way until /review caught it.
    const COS_PROMPT_SOURCES: &[(&str, &str)] = &[
        ("dev", include_str!("../cos.agents.toml")),
        (
            "overlay",
            include_str!("../../distro/overlay/etc/agentd/cos.agents.toml"),
        ),
        (
            "template:cos-inbox",
            include_str!("../../templates/cos-inbox.template.toml"),
        ),
        (
            "template:cos-curator",
            include_str!("../../templates/cos-curator.template.toml"),
        ),
    ];

    /// How many physical lines a single `kb_*(` call may span before `kb_calls` gives up.
    /// Generous: real calls are 1-2 lines, and an under-capture is a silent loss of coverage.
    const KB_CALL_MAX_SPAN: usize = 12;

    /// Blank out single- and double-quoted spans so punctuation inside a string literal cannot
    /// perturb paren balancing. `kb_put(segment='ops:x (y)', …)` balanced to zero on its first
    /// line without this, truncating the call and hiding every argument after it.
    fn strip_quoted(line: &str) -> String {
        let mut out = String::with_capacity(line.len());
        let mut quote: Option<char> = None;
        for c in line.chars() {
            match quote {
                Some(q) => {
                    if c == q {
                        quote = None;
                    }
                    out.push(' ');
                }
                None => {
                    if c == '\'' || c == '"' {
                        quote = Some(c);
                        out.push(' ');
                    } else {
                        out.push(c);
                    }
                }
            }
        }
        out
    }

    /// Collect each `kb_*(` call joined with its continuation lines, as
    /// `(1-based line number, joined call text, parens_balanced)`.
    ///
    /// A line-scoped `contains("kb_put") && contains("value=")` scan is silently defeated the
    /// moment a call's arguments wrap onto the next line: the `kb_put` token and the offending
    /// argument land on different lines and neither matches. That is not hypothetical — the
    /// first wrapped `kb_put(` in these files blinded this exact guard, and the mutation
    /// (`content=` → `value=` on the continuation line) still reported `ok`.
    ///
    /// The third tuple element is load-bearing: a call whose parens never balance inside the
    /// window is returned TRUNCATED, and a truncated call silently drops the arguments the
    /// guards exist to inspect. `kb_calls_never_silently_truncate` turns that into a loud
    /// failure; `kb_call_scanner_sees_wrapped_calls` is the positive/negative control pair.
    fn kb_calls(raw: &str) -> Vec<(usize, String, bool)> {
        let lines: Vec<&str> = raw.lines().collect();
        let mut calls = Vec::new();
        for (i, line) in lines.iter().enumerate() {
            if !line.contains("kb_put") && !line.contains("kb_get") && !line.contains("kb_search") {
                continue;
            }
            let mut joined = String::new();
            let mut depth: i32 = 0;
            let mut balanced = false;
            for l in lines.iter().skip(i).take(KB_CALL_MAX_SPAN) {
                joined.push_str(l);
                joined.push(' ');
                let bare = strip_quoted(l);
                depth += bare.matches('(').count() as i32;
                depth -= bare.matches(')').count() as i32;
                if depth <= 0 {
                    balanced = true;
                    break;
                }
            }
            calls.push((i + 1, joined, balanced));
        }
        calls
    }

    #[test]
    fn kb_call_scanner_sees_wrapped_calls() {
        // Negative control for `kb_calls`. If this ever passes vacuously, every guard built on
        // kb_calls has stopped guarding — which is the failure mode it exists to prevent.
        let wrapped = "  kb_put(segment='ops:entities', key='open:nothread:{slug}',\n\
                       \x20        value=<item text>)\n";
        let calls = kb_calls(wrapped);
        assert_eq!(calls.len(), 1, "expected one kb_put call, got {calls:?}");
        assert!(calls[0].2, "a 2-line call must balance inside the window");
        assert!(
            calls[0].1.contains("value="),
            "scanner must see `value=` on a kb_put continuation line; a line-scoped \
             contains(\"kb_put\") && contains(\"value=\") filter does not"
        );
        assert!(
            calls[0].1.contains("segment='ops:entities'"),
            "scanner must preserve args from the opening line too"
        );

        // A 5-line call: the previous 4-line window truncated this and let `value=` escape.
        let five = "  kb_put(\n    segment='ops:entities',\n    key='open:{thread_id}',\n\
                    \x20   # keep the item text verbatim\n    value=<item text>)\n";
        let c5 = kb_calls(five);
        assert_eq!(c5.len(), 1);
        assert!(c5[0].2, "a 5-line call must balance inside the window");
        assert!(
            c5[0].1.contains("value="),
            "scanner must reach the 5th line of a wrapped call"
        );

        // Parens inside a quoted string must not fake a balance and truncate the call.
        let quoted = "  kb_put(segment='ops:entities (thread-keyed)', key='k',\n\
                      \x20        value=<item text>)\n";
        let cq = kb_calls(quoted);
        assert_eq!(cq.len(), 1);
        assert!(cq[0].2, "quoted parens must not end the call early");
        assert!(
            cq[0].1.contains("value="),
            "a ')' inside a string literal must not truncate the scan"
        );

        // And an unterminated call must be REPORTED, not silently accepted.
        let unbalanced = "  kb_put(segment='ops:entities',\n";
        let cu = kb_calls(unbalanced);
        assert_eq!(cu.len(), 1);
        assert!(
            !cu[0].2,
            "an unterminated kb_ call must come back balanced=false so the guard can fail loudly"
        );
    }

    #[test]
    fn kb_calls_never_silently_truncate() {
        // If a real call ever outgrows the window, every guard built on kb_calls quietly stops
        // inspecting its arguments. Fail loudly instead.
        for (label, raw) in COS_PROMPT_SOURCES {
            for (line_no, joined, balanced) in kb_calls(raw) {
                assert!(
                    balanced,
                    "{label} line {line_no}: kb_* call's parens do not close within \
                     {KB_CALL_MAX_SPAN} lines, so the scanner truncated it and every guard built \
                     on kb_calls silently stopped covering it. Reformat the call or widen \
                     KB_CALL_MAX_SPAN. Captured: {joined}"
                );
            }
        }
    }

    #[test]
    fn cos_prompts_key_open_items_by_thread_not_date() {
        // brief.1: `open:{date}:{N}` mints a fresh KB key for the same item every morning, so
        // `ops:entities` accumulates a new entry per item per day forever. Keys must be
        // provider-native (Gmail threadId) with a deterministic slug fallback.
        //
        // NOTE this does NOT assert that handled items stop appearing in the brief — they do
        // not, and no test should imply otherwise. See the brief.1 HONESTY NOTE above the
        // cos-curator task and brief.2 in TODOS.md.
        for (label, raw) in COS_PROMPT_SOURCES {
            // Assert on the EXTRACTED CALLS, never on the raw file. `raw.contains("open:{thread_id}")`
            // is satisfied by a mere comment, so a prompt could key `open:item-{N}-{today}` and stay
            // green — brief.1's whole bug, reintroduced past its own guard (mutation-proven).
            // Checking the calls also makes this spelling-independent: any key template other than
            // the two allowed ones fails, so `{today}`/`{day}`/`{N}` cannot slip through a filter
            // that only knew about `{date}`/`{DATE}`.
            let open_calls: Vec<(usize, String)> = kb_calls(raw)
                .into_iter()
                .filter(|(_, call, _)| call.contains("kb_put") && call.contains("key='open:"))
                .map(|(n, call, _)| (n, call))
                .collect();
            // Only the curator-side sources key open items; the inbox side just emits the field.
            if raw.contains("key='open:") {
                assert!(
                    !open_calls.is_empty(),
                    "{label}: file mentions `key='open:` but kb_calls extracted no open-item \
                     kb_put — the scanner is not seeing the call it is supposed to guard"
                );
                for (n, call) in &open_calls {
                    let ok = call.contains("key='open:{thread_id}'")
                        || call.contains("key='open:nothread:{slug}'");
                    assert!(
                        ok,
                        "{label} line {n}: open item keyed by neither the provider-native \
                         `open:{{thread_id}}` nor the deterministic `open:nothread:{{slug}}` \
                         fallback. A date, an ordinal, or any model-chosen key re-creates the \
                         accumulate-forever bug brief.1 exists to fix. Call: {call}"
                    );
                }
                let has_thread = open_calls
                    .iter()
                    .any(|(_, c)| c.contains("key='open:{thread_id}'"));
                let has_slug = open_calls
                    .iter()
                    .any(|(_, c)| c.contains("key='open:nothread:{slug}'"));
                assert!(
                    has_thread && has_slug,
                    "{label}: needs BOTH the `open:{{thread_id}}` primary path and the \
                     `open:nothread:{{slug}}` fallback (found thread={has_thread} slug={has_slug})"
                );
            }
            assert!(
                raw.contains("thread_id"),
                "{label}: must carry `thread_id` per item — without it the curator has nothing \
                 provider-native to key by and the brief has nothing to link to"
            );
        }
    }

    #[test]
    fn cos_prompts_never_interpolate_unvalidated_thread_id_into_a_link() {
        // A Gmail permalink is the first clickable thing the brief ever contained, and
        // `thread_id` reaches the curator from a model that read untrusted email. Without a
        // charset guard, a value carrying ')' closes the markdown link early and the remainder
        // forges a second, attacker-chosen link in a document the operator is invited to click.
        // Only the two configs author the markdown brief; the templates do not.
        for (label, raw) in COS_PROMPT_SOURCES
            .iter()
            .filter(|(l, _)| *l == "dev" || *l == "overlay")
        {
            assert!(
                raw.contains("mail.google.com/mail/u/0/#all/{thread_id}"),
                "{label}: expected the Gmail permalink form; `#all/` survives archiving, \
                 which is what happens to a thread you finished replying to"
            );
            // Bind to the CONTROL SENTENCE, not the bare regex. `^[0-9a-f]{1,20}$` appears three
            // times per config (STEP 3 emit gate, STEP 2 key gate, STEP 4 link gate), so a
            // whole-file `contains` stayed green when the STEP 4 link rule was deleted outright
            // (mutation-proven). THREAT_MODEL.md §9.5 cites this test as the pin for that control,
            // so the pin has to actually hold.
            assert!(
                raw.contains(
                    "Emit a thread link ONLY when thread_id is a non-empty string matching \
                     ^[0-9a-f]{1,20}$"
                ),
                "{label}: the curator STEP 4 link rule is missing or reworded. The gate on an \
                 email-derived value entering a markdown href must be stated at the link site — \
                 THREAT_MODEL.md §9.5 names this test as what pins it"
            );
            assert!(
                raw.contains("emit a literal dash and do NOT put the value in the URL"),
                "{label}: the link rule needs its FAIL-CLOSED branch — without it a non-matching \
                 thread_id has no defined rendering and the model may interpolate it anyway"
            );
            // The other cells are sender-written too. thread_id was never the cheapest injection
            // path: a subject line reading `x [Pay now](https://evil.example)` needs no escape
            // trick at all. Pin the neutralisation rule that closes it.
            assert!(
                raw.contains("NEUTRALISE SENDER TEXT"),
                "{label}: `from`/`subject`/`ask`/`summary`/open-item text/`focus_recommendation` \
                 are all sender-written and land in markdown cells; the brief must neutralise \
                 markdown metacharacters in them, not just guard thread_id"
            );
            for entity in ["&#91;", "&#93;", "&#40;", "&#41;", "&#124;"] {
                assert!(
                    raw.contains(entity),
                    "{label}: the neutralisation rule must name the entity {entity} so the model \
                     has an exact substitution rather than a vague instruction to 'escape'"
                );
            }
        }
    }

    /// Regression: QA-1 — the OperatingBrief at its documented maxima must fit the store.
    /// Found by /qa on 2026-07-29 driving a real agentd against a fake provider.
    /// Report: .gstack/qa-reports/qa-report-agentos-cos-2026-07-29.md
    ///
    /// brief.1 added ~650 bytes of `thread_id` overhead without touching the caps, and the
    /// review's first fix was sized against RAW json — but the L1 path (`kb_put` on a scratch
    /// segment, `agentd/src/tools/native.rs`) measures the brief AFTER embedding it as a JSON
    /// string (every `"` becomes `\"`) inside a provenance wrapper. That is ~605 bytes of
    /// overhead here, which left only 39 bytes of real margin. Over the cap, the inbox write
    /// fails, the curator finds no input and stops, and the operator gets NO brief that morning.
    ///
    /// The caps below MIRROR the prompt. If you change one, change the other — the second half
    /// of this test fails if the prompt no longer states these numbers.
    #[test]
    fn cos_operating_brief_at_documented_maxima_fits_the_kb_entry_limit() {
        use crate::tools::native::MAX_MEM_CONTENT_BYTES;

        const MAX_IMPORTANT: usize = 6;
        const MAX_RESPONSE_NEEDED: usize = 8;
        const MAX_OPEN_ITEMS: usize = 10;
        const LEN_SUMMARY: usize = 100;
        const LEN_SUBJECT: usize = 80;
        const LEN_FROM: usize = 60;
        const LEN_OPEN_TEXT: usize = 100;
        const LEN_FOCUS: usize = 200;
        const LEN_DEADLINE: usize = 20;
        // Gmail thread ids are 16 hex chars in practice; the prompt bounds them at 20.
        const THREAD_ID: &str = "1a2b3c4d5e6f78901234";

        // `fill` lets the same shape be measured with ASCII or multi-byte text.
        let build = |n_imp: usize,
                     n_rn: usize,
                     n_oi: usize,
                     l_from: usize,
                     l_subj: usize,
                     l_body: usize,
                     l_oi: usize,
                     l_focus: usize,
                     fill: &dyn Fn(usize) -> String| {
            let brief = serde_json::json!({
                "date": "2026-07-30",
                "important": (0..n_imp).map(|_| serde_json::json!({
                    "from": fill(l_from), "subject": fill(l_subj), "summary": fill(l_body),
                    "urgency": "medium", "thread_id": THREAD_ID,
                })).collect::<Vec<_>>(),
                "response_needed": (0..n_rn).map(|_| serde_json::json!({
                    "from": fill(l_from), "subject": fill(l_subj), "ask": fill(l_body),
                    "deadline": "x".repeat(LEN_DEADLINE), "thread_id": THREAD_ID,
                })).collect::<Vec<_>>(),
                "open_items": (0..n_oi).map(|_| serde_json::json!({
                    "text": fill(l_oi), "thread_id": THREAD_ID,
                })).collect::<Vec<_>>(),
                "focus_recommendation": fill(l_focus),
                "omitted": { "important": 0, "response_needed": 0, "open_items": 0,
                             "truncated": false },
                "thread_count_reviewed": 50,
                "skipped_count": 30,
            });
            let content = serde_json::to_string(&brief).unwrap();
            // Exactly the scratch-class entry `kb_put` builds in tools/native.rs. `version` and
            // `turn` are modelled wide, and `ts` at full rfc3339 precision, so the model is
            // pessimistic rather than optimistic about the real wrapper.
            let entry = serde_json::to_string(&serde_json::json!({
                "content": content,
                "class": "scratch",
                "version": 999_999u64,
                "provenance": {
                    "agent_id": "cos-inbox-orchestrator-2026-07-30",
                    "turn": 999_999u64,
                    "task_fp": "ae32ccaf97a2ca2b",
                    "ts": "2026-07-30T08:00:01.123456789+00:00",
                    "citation": "msg-18f2c3a4b5d6e7f8",
                }
            }))
            .unwrap();
            (content.len(), entry.len())
        };

        let ascii = |n: usize| "x".repeat(n);
        // The prompt tells the model a non-ASCII field costs 2-3x and to truncate to roughly a
        // third. Model that literally: a CJK char is 3 bytes, so cap/3 chars fills the byte cap.
        let cjk = |n: usize| "中".repeat(n / 3);

        let (raw_ascii, wrapped_ascii) = build(
            MAX_IMPORTANT, MAX_RESPONSE_NEEDED, MAX_OPEN_ITEMS,
            LEN_FROM, LEN_SUBJECT, LEN_SUMMARY, LEN_OPEN_TEXT, LEN_FOCUS, &ascii,
        );
        let margin = MAX_MEM_CONTENT_BYTES as i64 - wrapped_ascii as i64;
        // 512 bytes is the floor, not a nicety: a longer agent id, a non-null citation, or a
        // handful of multi-byte characters in a real subject line all eat into it, and going
        // over costs the operator the entire brief.
        assert!(
            margin >= 512,
            "OperatingBrief at documented maxima wraps to {wrapped_ascii} bytes of \
             {MAX_MEM_CONTENT_BYTES} (margin {margin}); need >= 512 bytes spare. Raw json is \
             {raw_ascii} bytes — the wrapper and JSON-string escaping add ~600. Lower a cap in \
             BOTH cos.agents.toml copies and here, or the morning brief fails closed with no \
             operator-visible cause."
        );

        // QA-2 as an executable property, not prose: if a model obeys the prompt's "truncate a
        // non-ASCII field to roughly a third", the multi-byte brief must ALSO fit. Without this,
        // "in BYTES, not characters" is a sentence nothing enforces.
        let (_, wrapped_cjk) = build(
            MAX_IMPORTANT, MAX_RESPONSE_NEEDED, MAX_OPEN_ITEMS,
            LEN_FROM, LEN_SUBJECT, LEN_SUMMARY, LEN_OPEN_TEXT, LEN_FOCUS, &cjk,
        );
        assert!(
            wrapped_cjk as i64 <= MAX_MEM_CONTENT_BYTES as i64 - 512,
            "a CJK brief built to the prompt's own 'roughly a third' rule wraps to {wrapped_cjk} \
             bytes of {MAX_MEM_CONTENT_BYTES} — the byte-vs-character guidance does not actually \
             keep the brief inside the cap (QA-2)"
        );

        // QA-1's shrink ladder must actually RECOVER, not merely exist. Model its FLOOR rung
        // (STEP 4 rung 4: <=3 important + <=3 response_needed, from<=30 / subject<=40 only, no
        // open items, focus<=80) with the worst-case 3-byte-per-char fill. If the floor does not
        // fit, the ladder ends with the operator still getting nothing.
        let (_, wrapped_floor) = build(3, 3, 0, 30, 40, 0, 0, 80, &|n| "中".repeat(n));
        assert!(
            wrapped_floor as i64 <= MAX_MEM_CONTENT_BYTES as i64 - 2048,
            "the shrink ladder's FLOOR rung wraps to {wrapped_floor} bytes of \
             {MAX_MEM_CONTENT_BYTES} even before truncation — the ladder cannot recover, so an \
             over-size brief still ends with no brief at all"
        );

        // The prompt and these constants must not drift apart. Driven FROM the constants, so
        // adding a modelled field forces a prompt cross-check and raising a prompt cap fails
        // here. A hand-listed subset let `open_items ≤10` → `≤30` ship green while the real
        // entry was 1 765 bytes over the cap (mutation-proven).
        let caps: [(&str, usize); 9] = [
            ("important", MAX_IMPORTANT),
            ("response_needed", MAX_RESPONSE_NEEDED),
            ("open_items", MAX_OPEN_ITEMS),
            ("summaries/asks", LEN_SUMMARY),
            ("subjects", LEN_SUBJECT),
            ("from", LEN_FROM),
            ("open item text", LEN_OPEN_TEXT),
            ("deadline", LEN_DEADLINE),
            ("focus_recommendation", LEN_FOCUS),
        ];
        for (label, raw) in COS_PROMPT_SOURCES
            .iter()
            .filter(|(l, _)| *l == "dev" || *l == "overlay")
        {
            // Whitespace-tolerant and `<=`-tolerant: reformatting `≤6` to `≤ 6` is a no-op change
            // that must not fail, or the next author deletes the assertion instead of fixing it.
            let flat = raw
                .replace("<=", "≤")
                .replace(" ≤", "≤")
                .replace("≤ ", "≤")
                .replace('\n', " ");
            for (name, n) in caps {
                let needle = format!("{name}≤{n}");
                assert!(
                    flat.contains(&needle),
                    "{label}: prompt does not state `{name} ≤{n}`, but this test's byte budget \
                     assumes it. Every modelled cap must be pinned to the prompt text — a cap \
                     that drifts upward silently reintroduces QA-1."
                );
            }
            assert!(
                raw.contains("in BYTES, not characters"),
                "{label}: the caps must be stated in bytes — the store measures bytes, so a CJK \
                 subject at a character cap silently blows the limit (QA-2)"
            );
            // BOTH enforcement points, not just L1: production routes through the sidecar under
            // `tool_override = true`, and that path says "content too large". Pinning only the
            // L1 phrase let the production trigger be deleted green (mutation-proven).
            for phrase in ["entry too large", "content too large"] {
                assert!(
                    raw.contains(phrase),
                    "{label}: the shrink-and-retry ladder keys off the runtime's error text, so \
                     it must name BOTH `entry too large` (L1) and `content too large` (the \
                     Qdrant sidecar, which is the path production actually uses); `{phrase}` is \
                     missing"
                );
            }
            assert!(
                raw.contains("'omitted'"),
                "{label}: a shrunk brief MUST record what it dropped — otherwise the ladder turns \
                 a loud failure into a brief that looks complete and is not"
            );
        }
    }

    /// The two size caps that bound the SAME payload live in two languages and must agree:
    /// `MAX_MEM_CONTENT_BYTES` (Rust, L1) and `HIT_CONTENT_CAP` (Python, the Qdrant sidecar that
    /// production actually routes through under `tool_override = true`). Nothing else pins them
    /// together, so they could drift and make the byte-budget guard above measure the wrong limit.
    #[test]
    fn kb_size_caps_agree_across_both_backends() {
        use crate::tools::native::MAX_MEM_CONTENT_BYTES;
        let sidecar = include_str!("../../docker/semantic_kb_mcp.py");
        let line = sidecar
            .lines()
            .find(|l| l.trim_start().starts_with("HIT_CONTENT_CAP"))
            .expect("semantic_kb_mcp.py must define HIT_CONTENT_CAP");
        // e.g. `HIT_CONTENT_CAP  = 8 * 1024          # 8 KB per hit`
        let expr = line.split('=').nth(1).unwrap().split('#').next().unwrap().trim();
        let value: usize = expr
            .split('*')
            .map(|p| p.trim().parse::<usize>().expect("numeric HIT_CONTENT_CAP factors"))
            .product();
        assert_eq!(
            value, MAX_MEM_CONTENT_BYTES,
            "HIT_CONTENT_CAP ({value}) != MAX_MEM_CONTENT_BYTES ({MAX_MEM_CONTENT_BYTES}). The \
             same OperatingBrief is size-checked by both, so a divergence means the prompt's caps \
             are correct for one deployment and wrong for the other."
        );
    }

    #[test]
    fn cos_prompts_use_content_not_value_for_kb_put() {
        // kb_put requires `content`; `value` is silently dropped by additionalProperties:false
        // and the write never persists. Fixed in the configs at v0.77.0 — but the guard was
        // scoped to two files, so the templates kept shipping `value=` for ~40 releases.
        for (label, raw) in COS_PROMPT_SOURCES {
            let bad: Vec<usize> = kb_calls(raw)
                .into_iter()
                .filter(|(_, call, _)| call.contains("kb_put") && call.contains("value="))
                .map(|(n, _, _)| n)
                .collect();
            assert!(
                bad.is_empty(),
                "{label}: kb_put uses 'value=' at line(s) {bad:?}; the parameter is 'content=' \
                 and 'value=' is silently dropped, so the write never persists"
            );
        }
    }

    #[test]
    fn cos_agents_toml_parses_cleanly() {
        let raw = include_str!("../cos.agents.toml");
        let _cfg: Config = toml::from_str(raw)
            .expect("cos.agents.toml must parse as a valid Config");
        let overlay_raw = include_str!("../../distro/overlay/etc/agentd/cos.agents.toml");
        let _overlay_cfg: Config = toml::from_str(overlay_raw)
            .expect("distro overlay cos.agents.toml must parse as a valid Config");
    }

    #[test]
    fn cos_agents_toml_google_oauth_server_has_credential_capability() {
        // Broker mode (cred.6): main.rs builds the credential proxy token's
        // allowed_providers list from the google_oauth MCP SERVER's own
        // `capabilities` (not the agent-level capabilities list, which grants
        // Credential separately for a different check). Omitting it here means
        // every google_oauth API call is rejected with
        // credential_denied/no_providers_configured even though the OAuth
        // session itself is valid — found live testing the CoS Inbox agent.
        use crate::capability::CredentialProvider;

        let dev_raw = include_str!("../cos.agents.toml");
        let overlay_raw = include_str!("../../distro/overlay/etc/agentd/cos.agents.toml");
        for (label, raw) in [("dev", dev_raw), ("overlay", overlay_raw)] {
            let cfg: Config = toml::from_str(raw).expect("must parse");
            let server = cfg
                .tools
                .mcp_servers
                .iter()
                .find(|s| s.name == "google_oauth")
                .unwrap_or_else(|| panic!("{label}: no google_oauth MCP server defined"));
            let has_credential_cap = server
                .capabilities
                .as_ref()
                .map(|caps| {
                    caps.iter().any(|c| {
                        matches!(
                            c,
                            Capability::Credential { provider: CredentialProvider::Google }
                        )
                    })
                })
                .unwrap_or(false);
            assert!(
                has_credential_cap,
                "{label}: google_oauth MCP server must have its own \
                 {{ Credential = {{ provider = \"Google\" }} }} capability (broker mode) — \
                 the agent-level Credential grant does not cover this",
            );
        }
    }

    #[test]
    fn cos_agents_toml_kb_segments_are_known() {
        // Derive valid segment names from the parsed [[memory.segments]] config —
        // no hardcoded list. Adding a new segment to [[memory.segments]] automatically
        // allows it here; no Rust changes needed.
        let dev_raw = include_str!("../cos.agents.toml");
        let cfg: Config = toml::from_str(dev_raw).expect("must parse");
        let known: Vec<&str> = cfg.memory.segments.iter().map(|s| s.name.as_str()).collect();

        let overlay_raw = include_str!("../../distro/overlay/etc/agentd/cos.agents.toml");
        for (label, raw) in [("dev", dev_raw), ("overlay", overlay_raw)] {
            // Joined calls, so a wrapped `segment='...'` argument stays in scope.
            for (line_no, call, _) in kb_calls(raw) {
                // EVERY `segment='` in the joined block, not just the first: joining can merge
                // two calls into one entry, and a single line can carry two calls — either way a
                // "check the first occurrence" scan leaves the rest unvalidated.
                let mut rest = call.as_str();
                while let Some(start) = rest.find("segment='") {
                    let after = &rest[start + 9..];
                    let end = after.find('\'').unwrap_or_else(|| {
                        panic!(
                            "{label} line {line_no}: `segment='` has no closing quote inside the \
                             captured call — the scanner cannot validate it, so fail loudly \
                             instead of skipping: {call}"
                        )
                    });
                    let seg = &after[..end];
                    assert!(
                        known.contains(&seg),
                        "{label} line {line_no}: unknown segment '{seg}'; \
                         valid segments are {known:?} — add it to [[memory.segments]] in cos.agents.toml"
                    );
                    rest = &after[end..];
                }
            }
        }
    }

    #[test]
    fn cos_agents_toml_curator_requires_markdown_content() {
        // cap.2b moved brief assembly from the orchestrator prompt into the cos-curator [[jobs]]
        // task. The instruction that write_file content be formatted markdown (not raw JSON)
        // must survive that move — a JSON blob written as the brief is the classic regression.
        let dev_raw = include_str!("../cos.agents.toml");
        let overlay_raw = include_str!("../../distro/overlay/etc/agentd/cos.agents.toml");
        for (label, raw) in [("dev", dev_raw), ("overlay", overlay_raw)] {
            assert!(
                raw.contains("MUST be formatted markdown"),
                "{} cos.agents.toml cos-curator job must instruct that write_file content is \
                 formatted markdown, not JSON",
                label
            );
        }
    }
}
